vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:

        photo_file:
            uri_prefix: assets/images
            upload_destination: '%kernel.project_dir%/public/assets/images/'

        profile_picture:
            uri_prefix: /images/profile
            upload_destination: '%kernel.project_dir%/public/images/profile'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
